hue:
  url: ${tools.hue.uri}
  available: ${tools.hue.available}

arcadia:
  url: ${tools.arcadia.uri}
  available: ${tools.arcadia.available}

cf:
  resource: ${sso.apiEndpoint}
  uaa: ${vcap.services.sso.credentials.uaaUri}

security:
  ignored: /open,/sdoc.jsp,/*.js,/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/v2/api-docs

spring.oauth2:
  resource:
    id: cloud_controller
    jwt:
      keyUri: ${sso.tokenKey}

logging:
  level:
    org.springframework.security: DEBUG
    org.trustedanalytics: DEBUG

endpoints.enabled: false
endpoints.health.enabled: true
